turtlebot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Effort Controllers ---------------------------------------
  wheel_right_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_right_joint
    pid: {p: 100.0, i: 0.01, d: 0.00}
  wheel_left_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_left_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}

  # Velocity Controllers ---------------------------------------

  # wheel_right_velocity_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: wheel_right_joint
  #   pid: {p: 0.4, i: 0.0, d: 0.0}
  # wheel_left_velocity_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: wheel_left_joint
  #   pid: {p: 0.4, i: 0.0, d: 0.0}